// Generated by CoffeeScript 1.6.2
(function() {
  var client, createHash, fs, randobet;

  fs = require("fs");

  client = require("capture/client");

  randobet = function(n) {
    var a, i, s;

    a = ('abcdefghijklmnopqrstuvwxyz' + 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' + '0123456789').split('');
    s = (function() {
      var _i, _results;

      _results = [];
      for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
        _results.push(a[Math.random() * a.length | 0]);
      }
      return _results;
    })();
    return s.join('');
  };

  createHash = function(model, callback) {
    var hash;

    hash = randobet(12);
    return model.find({
      hash: hash
    }).done(function(err, result) {
      if (result == null) {
        return callback(hash);
      } else {
        return createHash();
      }
    });
  };

  module.exports = {
    upload: function(req, res) {
      var type;

      if (/image\/p?jpe?g/.test(req.files.image.type)) {
        type = 'jpg';
      } else if (/image\/(x-)?png/.test(req.files.image.type)) {
        type = 'png';
      } else if (/image\/gif/.test(req.files.image.type)) {
        type = 'gif';
      } else {
        type = 'unk';
      }
      if (type !== 'unk') {
        return fs.readFile(req.files.image.path, function(err, data) {
          var save;

          if (!err) {
            save = function(hash) {
              return Tmp.create({
                hash: hash,
                image: data,
                type: type
              }).done(function(err, img) {
                if (!err) {
                  return res.view("pages/upload", {
                    status: 'success',
                    image: "\"/t/" + hash + "\""
                  });
                } else {
                  return res.view("pages/upload", {
                    status: 'exception'
                  });
                }
              });
            };
            return createHash(Tmp, save);
          } else {
            return res.view("pages/upload", {
              status: 'exception'
            });
          }
        });
      } else {
        return res.view("pages/upload", {
          status: 'unsupportedimage'
        });
      }
    },
    share: function(req, res) {
      var dna, runClient, tmpHash;

      dna = req.param('dna');
      runClient = function(dna) {
        var myClient;

        myClient = new client(dna);
        return myClient.run(function(data64) {
          var data, save;

          data = new Buffer(data64.toString(), 'base64');
          save = function(hash) {
            return Image.create({
              hash: hash,
              image: data
            }).done(function(err, img) {
              if (!err) {
                return res.json({
                  status: 'success',
                  hash: hash
                });
              } else {
                return res.json({
                  status: 'failure'
                });
              }
            });
          };
          return createHash(Image, save);
        });
      };
      if (req.param('hasTmpImage')) {
        tmpHash = dna.image.split('/').pop();
        return Tmp.find({
          hash: tmpHash
        }).done(function(err, img) {
          if (!err) {
            dna.image = ("data:" + img.type + ";base64,") + img.image.toString("base64");
            return runClient(dna);
          } else {
            return res.json({
              status: 'failure'
            });
          }
        });
      } else {
        return runClient(dna);
      }
    },
    show: function(req, res) {
      return Image.find({
        hash: req.param('hash')
      }).done(function(err, img) {
        if (!err) {
          if (img != null) {
            res.setHeader('Content-Type', 'image/png');
            res.setHeader('Expires', new Date(Date.now() + 60 * 60 * 24 * 365 * 1000).toUTCString());
            return res.end(img.image);
          } else {
            return res.view('404');
          }
        } else {
          return res.view('500');
        }
      });
    },
    tmp: function(req, res) {
      return Tmp.find({
        hash: req.param('hash')
      }).done(function(err, img) {
        if (!err) {
          if (img != null) {
            res.setHeader('Content-Type', "image/" + img.type);
            res.setHeader('Expires', new Date(Date.now() + 60 * 60 * 24 * 365 * 1000).toUTCString());
            return res.end(img.image);
          } else {
            return res.view('404');
          }
        } else {
          return res.view('500');
        }
      });
    }
  };

}).call(this);
