// Generated by CoffeeScript 1.6.2
(function() {
  var cronJob, dateformat, sv;

  cronJob = require('cron').CronJob;

  sv = require('local_shared_values');

  dateformat = require('dateformat');

  module.exports.bootstrap = function(cb) {
    new cronJob('0 0 * * * *', function() {
      var date, expire;

      if (typeof Image === "undefined" || Image === null) {
        return;
      }
      date = new Date((new Date).getTime() - 60 * 60 * 24 * 1000);
      expire = dateformat(date, "yyyy-mm-dd HH:MM:ss");
      Image.destroy({
        createdAt: {
          '<': expire
        },
        tmp: 1
      }, function(err, img) {
        if (!err) {
          return console.log('cleanedUp');
        } else {
          return console.log('err');
        }
      });
      date = new Date((new Date).getTime() - sv.imageMaxAge);
      expire = dateformat(date, "yyyy-mm-dd HH:MM:ss");
      return Image.destroy({
        createdAt: {
          '<': expire
        },
        tmp: 0
      }, function(err, img) {
        if (!err) {
          return console.log('cleanedUp');
        } else {
          return console.log('err');
        }
      });
    }, null, true);
    return cb();
  };

}).call(this);
