// Generated by CoffeeScript 1.6.2
(function() {
  var cronJob;

  cronJob = require('cron').CronJob;

  module.exports.bootstrap = function(cb) {
    new cronJob('* * * * * *', function() {
      if (typeof Image === "undefined" || Image === null) {
        return;
      }
      return console.log(Image);
    }, null, true);
    return cb();
  };

}).call(this);
